# Stage 1: Build stage
FROM python:3.9-slim as builder

WORKDIR /weather_app
COPY ../WeatherApp/app /weather_app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt && rm -f requirements.txt

RUN pip install gunicorn


# Stage 2: Production stage
FROM builder 

# Copy the application source code from the previous stage
#COPY --from=builder /weather_app /weather_app/

EXPOSE 5000
#ARG BG_COLOR
ENV BG_COLOR="GREEN"

CMD gunicorn --bind 0.0.0.0:5000 wsgi:app 


