apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.weatherApp.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.weatherApp.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.weatherApp.service.port }}
      targetPort: {{ .Values.weatherApp.service.targetPort }}
      nodePort: {{ .Values.weatherApp.service.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.nginx.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      nodePort: {{ .Values.nginx.service.nodePort }}

