name: Bump Version and Tag

on:
  push:
    branches:
    - main

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Bump version
      id: bump_version
      run: |
        current_version=$(cat VERSION)
        IFS='.' read -r -a version_parts <<< "$current_version"
        version_parts[2]=$((version_parts[2]+1))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"
        echo $new_version > VERSION
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Commit and push new version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to ${{ env.new_version }}"
        git push

    - name: Create tag
      run: |
        git tag -a v${{ env.new_version }} -m "Version ${{ env.new_version }}"
        git push origin v${{ env.new_version }}
