name: Bump Version and Tag

on:
  workflow_run:
    workflows: ["WeatherApp CI/CD"]
    types:
    - completed

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ensure VERSION file exists
      run: ls -la WeatherApp/app/

    - name: Bump version
      id: bump_version
      run: |
        current_version=$(cat WeatherApp/app/VERSION)
        IFS='.' read -r -a version_parts <<< "$current_version"
        version_parts[2]=$((version_parts[2]+1))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"
        echo $new_version > WeatherApp/app/VERSION
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Commit and push new version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add WeatherApp/app/VERSION
        git commit -m "Bump version to ${{ env.new_version }}"
        git push

    - name: Create tag
      run: |
        git tag -a v${{ env.new_version }} -m "Version ${{ env.new_version }}"
        git push origin v${{ env.new_version }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myweatherapp:latest

    - name: Tag Docker Image with New Version
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/myweatherapp:latest ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ env.new_version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ env.new_version }}

