name: Download and Use Artifact

on:
  repository_dispatch:
    types: [start-release]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Wait for a few seconds
      run: sleep 5

    - name: Check DNS Resolution
      run: nslookup index.docker.io

    - name: List files for debugging before downloading artifact
      run: |
        echo "Files before downloading artifact:"
        ls -R

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded_artifacts

    - name: Verify Downloaded Artifacts
      run: |
        echo "Downloaded artifacts:"
        ls -R downloaded_artifacts

    - name: Load Docker Image Tag
      run: echo "DOCKER_IMAGE_TAG=$(cat downloaded_artifacts/image_tag.txt)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ env.DOCKER_IMAGE_TAG }}

    - name: Zip the build artifacts
      run: zip -r build.zip downloaded_artifacts/

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
