name: Continuous Deployment

on:
  push:
    branches: [main]
    paths:
    - 'WeatherApp/**'
  pull_request:
    branches: [main]
    paths:
    - 'WeatherApp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Push Docker Image to Registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push myweatherapp:latest

    - name: Update Helm Chart and Deploy
      run: |
        # Update Helm Chart here, e.g., bump version
        # Deploy via ArgoCD, or another deployment tool
