name: Continuous Integration

on:
  push:
    branches: [main]
    paths:
    - 'WeatherApp/**'
  pull_request:
    branches: [main]
    paths:
    - 'WeatherApp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r WeatherApp/app/requirements.txt

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 WeatherApp/app/

    - name: Build Docker Image
      run: docker build -t myweatherapp:${{ github.sha }} -f WeatherApp/deploy/Dockerfile .

    - name: Save Dockerfile and requirements.txt for Later Jobs
      uses: actions/upload-artifact@v2
      with:
        name: docker-image-files
        path: |
          WeatherApp/deploy/Dockerfile
          WeatherApp/app/requirements.txt

    - name: Trigger CD Workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: start-cd
