name: Build and Upload Artifact

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Save Docker Image Tag to File
      run: echo "${{ github.sha }}" > image_tag.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          image_tag.txt
          helm_charts_weatherapp/

    - name: Trigger Release Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        event-type: start-release
