name: Continuous Integration

on:
  push:
    branches: [main]
    paths:
    - 'WeatherApp/**'
  pull_request:
    branches:
    - main
    paths:
    - 'WeatherApp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r WeatherApp/app/requirements.txt

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 WeatherApp/app/

    - name: Build Docker Image
      run: docker build -t myweatherapp:${{ github.sha }} -f WeatherApp/deploy/Dockerfile .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag myweatherapp:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ github.sha }}

    - name: Save Docker Image Tag to File
      run: echo "${{ github.sha }}" > image_tag.txt

    - name: Upload Image Tag and Helm Chart Files
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          image_tag.txt
          helm_charts_weatherapp/

    - name: List uploaded artifacts
      run: |
        echo "Uploaded artifacts:"
        ls -R

    - name: List "uploaded artifacts"
      run: |
        echo "Uploaded artifacts:"
        ls -R

    - name: List uploaded artifacts
      run: |
        echo "Uploaded artifacts:"
        ls -R
        echo "Artifact details:"
        find . -name 'build-files'

    # - name: Trigger CD Workflow
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.PAT }}
    #     event-type: start-cd
