name: WeatherApp CI/CD

on:
  push:
    branches: [main]
    paths:
    - 'WeatherApp/**'
  pull_request:
    branches:
    - main
    paths:
    - 'WeatherApp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: WeatherApp/app/scripts/set_env.sh
      env:
        KEY_API: ${{ secrets.KEY_API }}
        BG_COLOR: ${{ secrets.BG_COLOR }}

    - name: Write environment variables to .env file
      run: WeatherApp/app/scripts/write_env.sh
      env:
        KEY_API: ${{ secrets.KEY_API }}
        BG_COLOR: ${{ secrets.BG_COLOR }}

    - name: Print working directory
      run: pwd

    - name: Ensure .env file exists
      run: ls -la

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          .env


  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded_artifacts

    - name: Build Docker Image
      run: docker build -t myweatherapp:${{ github.sha }} -f WeatherApp/deploy/Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name myweatherapp --env-file downloaded_artifacts/.env myweatherapp:${{ github.sha }}

    - name: Wait for the server to be ready
      run: |
        echo "Waiting for server to start..."
        for i in {1..3}; do
          if curl --silent --fail http://127.0.0.1:5000/; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server..."
          sleep 5
        done

    - name: Print Docker logs for debugging
      run: docker logs myweatherapp

    - name: Install Python Dependencies
      run: pip install pytest selenium webdriver-manager

    - name: Run Selenium tests
      run: xvfb-run --server-args="-screen 0 1920x1080x24" pytest WeatherApp/app/test/test_weather_app.py

    - name: Stop and remove Docker container
      run: |
        docker stop myweatherapp
        docker rm myweatherapp

  bump_and_deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded_artifacts

    - name: Load Docker Image Tag
      run: echo "DOCKER_IMAGE_TAG=$(cat downloaded_artifacts/image_tag.txt)" >> $GITHUB_ENV

    - name: Bump version
      id: bump_version
      run: WeatherApp/app/scripts/bump_version.sh
      env:
        GITHUB_ENV: $GITHUB_ENV

    - name: Commit and push new version
      run: WeatherApp/app/scripts/commit_and_push_version.sh

    - name: Create tag
      run: WeatherApp/app/scripts/create_git_tag.sh

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image with New Version
      run: |
        new_version=$(cat VERSION)
        docker tag ${{ secrets.DOCKER_USERNAME }}/myweatherapp:latest ${{ secrets.DOCKER_USERNAME }}/myweatherapp:$new_version
        docker push ${{ secrets.DOCKER_USERNAME }}/myweatherapp:$new_version
