name: WeatherApp CI/CD

on:
  push:
    branches: [main]
    paths:
    - 'WeatherApp/**'
  pull_request:
    branches:
    - main
    paths:
    - 'WeatherApp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "KEY_API=${{ secrets.KEY_API }}" >> $GITHUB_ENV
        echo "BG_COLOR=${{ secrets.BG_COLOR }}" >> $GITHUB_ENV

    - name: Write environment variables to .env file
      run: |
        echo "KEY_API=${{ secrets.KEY_API }}" >> .env
        echo "BG_COLOR=${{ secrets.BG_COLOR }}" >> .env

    - name: Print .env file for debugging
      run: cat .env

    - name: Save .env file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        path: .env

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r WeatherApp/app/requirements.txt

      # - name: Lint with Flake8
      #   run: |
      #     pip install flake8
      #     flake8 WeatherApp/app/
    - name: Build Docker Image
      run: docker build -t myweatherapp:${{ github.sha }} -f WeatherApp/deploy/Dockerfile .

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded_artifacts

    - name: Download .env file
      uses: actions/download-artifact@v4
      with:
        name: env-file
        path: .

    - name: Print .env file for debugging
      run: cat .env

    - name: Load Docker Image Tag
      run: echo "DOCKER_IMAGE_TAG=$(cat downloaded_artifacts/image_tag.txt)" >> $GITHUB_ENV

    - name: Ensure .env file exists
      run: ls -la

    - name: Run Docker container with .env file
      run: docker run -d -p 5000:5000 --name myweatherapp --env-file .env myweatherapp:${{ env.DOCKER_IMAGE_TAG }}

    - name: Wait for the server to be ready
      run: |
        echo "Waiting for server to start..."
        for i in {1..10}; do
          if curl --silent --fail http://127.0.0.1:5000/; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server..."
          sleep 5
        done

    - name: Print Docker logs for debugging
      run: docker logs myweatherapp

    - name: Install Python Dependencies
      run: pip install pytest selenium webdriver-manager

    - name: Run Selenium tests
      run: xvfb-run --server-args="-screen 0 1920x1080x24" pytest WeatherApp/app/test/test_weather_app.py

    - name: Stop and remove Docker container
      run: |
        docker stop myweatherapp
        docker rm myweatherapp


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./downloaded_artifacts

    - name: Load Docker Image Tag
      run: echo "DOCKER_IMAGE_TAG=$(cat downloaded_artifacts/image_tag.txt)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myweatherapp:${{ env.DOCKER_IMAGE_TAG }}

    # - name: Update Helm Chart and Deploy with ArgoCD
    #   run: |
    #     VERSION=${{ env.DOCKER_IMAGE_TAG }}
    #     helm upgrade --install myweatherapp ./downloaded_artifacts/helm_charts_weatherapp --set image.tag=$VERSION
    #     argocd app sync myweatherapp --revision $VERSION
