name: Share data between jobs

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        expr 3 + 7 > math-homework.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v4
      with:
        name: homework
        path: math-homework.txt

  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v4
      with:
        name: homework
    - shell: bash
      run: |
        value=`cat math-homework.txt`
        expr $value \* 9 > math-homework1.txt
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v4
      with:
        name: homework
        path: math-homework1.txt

  job_3:
    needs: job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v4
      with:
        name: homework
    - shell: bash
      run: |
        value=`cat math-homework.txt`
        echo The result is $value
